[pytest]                    # секция конфигурации pytest
markers =                   # регистрация кастомных маркеров
    smoke: быстрые тесты
    regression: полный регресс
# искать тесты только в папке tests
testpaths = tests
# автоматически добавлять флаги -s -v --alluredir=allure-results  при каждом запуске, а для allure запускать allure serve allure-results
addopts = -s -v --alluredir=allure-results --clean-alluredir